<a href="https://colab.research.google.com/github/deepsh7991/Data-sicence-projects/blob/main/Sentiment%2BAnalysis_use%2BCase_text%2Bclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sentences = ['Rashmi likes ice cream', 'Rashmi hates chocolate.']

In [ ]:
vectorizer = CountVectorizer(min_df=0, lowercase=False)
vectorizer.fit(sentences)
vectorizer.vocabulary_

{'Rashmi': 0, 'likes': 5, 'ice': 4, 'cream': 2, 'hates': 3, 'chocolate': 1}

In [ ]:
vectorizer.transform(sentences).toarray()

array([[1, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0]], dtype=int64)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\Sasmita\Downloads\amazon_unlocked_mobile (1).csv')
df.head()

In [ ]:
df.dropna(inplace=True)
df=df[df['rating']!=3]
df['Positively Rated'] = np.where(df['rating']>3,1,0)
df.head(10)

product_name brand_name   price  \
0   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
5   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
6   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
7   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
8   "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
11  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

    rating                                            reviews  review_votes  \
0        5  I feel so LUCKY to have found this used (phone...           1.0   
1        4  nice phone, nice up grade from my pantach revu...           0.0   
2        5                                       Very pleased           0.0   
3        4  It works good but it goes slow sometimes but i...           0.0   
4        4  Great phone to replace my lost phone. The only...           0.0   
5        1  I already had a phone with problems... I know ...           1.0   
6        2  The charging port was loose. I got that solder...           0.0   
7        2  Phone looks good but wouldn't stay charged, ha...           0.0   
8        5  I originally was using the Samsung S2 Galaxy f...           0.0   
11       5  This is a great product it came after two days...           0.0   

    Positively Rated  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1  
5                  0  
6                  0  
7                  0  
8                  1  
11                 1

In [ ]:
df['Positively Rated'].mean()

0.7482686025879323

In [ ]:
df.shape

(308277, 7)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['reviews'],df['Positively Rated'],random_state=0)

In [ ]:
X_train.shape

(231207,)

In [ ]:
print('X_train first entry: \n\n',X_train[0])

X_train first entry: 

 I feel so LUCKY to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. My Son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! Thank you Seller, we really appreciate it & your honesty re: said used phone.I recommend this seller very highly & would but from them again!!


In [ ]:
X_train.shape

(231207,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer().fit(X_train)

In [ ]:
vect.tokenizer

In [ ]:
vect.get_feature_names()[::2000]

['00',
 '4less',
 'adr6275',
 'assignment',
 'blazingly',
 'cassettes',
 'condishion',
 'debi',
 'dollarsshipping',
 'esteem',
 'flashy',
 'gorila',
 'human',
 'irullu',
 'like',
 'microsaudered',
 'nightmarish',
 'p770',
 'poori',
 'quirky',
 'responseive',
 'send',
 'sos',
 'synch',
 'trace',
 'utiles',
 'withstanding']

In [ ]:
len(vect.get_feature_names())

53216

In [ ]:
X_trained_vectorized = vect.transform(X_train)
X_trained_vectorized.shape

(231207, 53216)

In [ ]:
X_trained_vectorized

<231207x53216 sparse matrix of type '<class 'numpy.int64'>'
	with 6117776 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_trained_vectorized,y_train)

C:\Users\Sasmita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Sasmita\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
from keras.models import Sequential
from keras import layers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.wrappers.scikit_learn import KerasClassifier


In [ ]:
X_trained_vectorized.shape

(231207, 198917)

In [ ]:
input_dim = 198917  # Number of features

model = Sequential()
model.add(layers.Dense(10, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                1989180   
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 1,989,191
Trainable params: 1,989,191
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# history = model.fit(X_trained_vectorized,y_train,
#                     epochs=100,
#                     verbose=True,
#                     validation_data=(vect.transform(X_test), y_test),
#                     batch_size=10)

In [ ]:
# loss, accuracy = model.evaluate(X_train, y_train, verbose=False)
# print("Training Accuracy: {:.4f}".format(accuracy))
# loss, accuracy = model.evaluate(X_test, y_test, verbose=False)
# print("Testing Accuracy:  {:.4f}".format(accuracy))

In [ ]:
# def plot_history(history):
#     acc = history.history['acc']
#     val_acc = history.history['val_acc']
#     loss = history.history['loss']
#     val_loss = history.history['val_loss']
#     x = range(1, len(acc) + 1)

#     plt.figure(figsize=(12, 5))
#     plt.subplot(1, 2, 1)
 #     plt.plot(x, val_acc, 'r', label='Validation acc')
#     plt.title('Training and validation accuracy')
#     plt.legend()
#     plt.subplot(1, 2, 2)
#     plt.plot(x, loss, 'b', label='Training loss')
#     plt.plot(x, val_loss, 'r', label='Validation loss')
#     plt.title('Training and validation loss')
#     plt.legend()

In [ ]:
#plot_history(history)

In [ ]:
----prediction---what is the input in prediction?

In [ ]:
from sklearn.metrics import roc_auc_score
predictions = model.predict(vect.transform(X_test))

#print('AUC:', roc_auc_score(y_test, predictions))


In [ ]:
predictions 

array([1, 0, 1, ..., 0, 1, 1])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer.fit(X_train)
len(vect.get_feature_names())

In [ ]:
/= vect.transform(X_train)

model = LogisticRegression()
model.fit(X_trained_vectorized,y_train)

predictions = model.predict(vect.transform(X_test))

print('AUC:', roc_auc_score(y_test, predictions))



In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

In [ ]:
print(model.predict(vect.transform(['not an issue, phone is working','this is a nice phone', 'an isssue, phone is not working'])))

[0 1 0]


In [ ]:
vect = CountVectorizer(min_df=5,ngram_range=(1,2)).fit(X_train)
X_trained_vectorized = vect.transform(X_train)


In [ ]:
model = LogisticRegression()
model.fit(X_trained_vectorized,y_train)

predictions = model.predict(vect.transform(X_test))

print('AUC:', roc_auc_score(y_test, predictions))



C:\Users\Sasmita\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Sasmita\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


AUC: 0.9651416870431984


In [ ]:
print(model.predict(vect.transform(['not an issue, phone is working', 'an isssue, phone is not working'])))

[1 0]
